[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.production.environment]
  NODE_VERSION = "18"
   VITE_API_URL = https://gestionenmovilidad.netlify.app/
   JWT_SECRET = "tu_secreto_real"