[build]
  command = "npm --prefix client install && npm --prefix client run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"  # Usa tu versión de Node