[build]
  command = "npm run build"  # Ejecuta desde raíz
  publish = "client/dist"           # Directorio de salida de Vite
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Fuerza SPA mode

[context.production.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "http://localhost:5173"  