[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "dist"  # Changed from "client/dist" to "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"